ci: optimize ci/cd workflow

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -24,17 +24,12 @@ jobs:
         run: |
           echo "run-with-secrets=${{ steps.detect-secrets.outputs.has-secrets == 'true' && !github.event.repository.fork }}" >> $GITHUB_OUTPUT
 
-  staging-repo:
+  precompute-next-version:
     runs-on: ubuntu-24.04
-    needs:
-      - check-secrets
-    if: needs.check-secrets.outputs.run-with-secrets == 'true'
     outputs:
-      maven-central-repo-id: ${{ steps.staging-repo.outputs.MavenCentral }}
       next-version: ${{ steps.compute-next-version.outputs.next-version }}
-      will-release: ${{ steps.compute-next-version.outputs.will-release }}
     steps:
-      - name: Checkout the repo
+      - name: Checkout
         uses: actions/checkout@v4.2.2
         with:
           fetch-depth: 0
@@ -43,81 +38,48 @@ jobs:
         uses: nicolasfara/precompute-semantic-release-version-action@2.0.2
         with:
           github-token: ${{ github.token }}
-      - uses: DanySK/build-check-deploy-gradle-action@3.5.25
-        with:
-          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
-          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          should-run-codecov: false
-          should-deploy: true
-          build-command: true
-          check-command: true
-          deploy-command: |
-            if [[ "${{ steps.compute-next-version.outputs.will-release }}" == "true" ]]; then
-              ./gradlew -PforceVersion="${{ steps.compute-next-version.outputs.next-version }}" createStagingRepositoryOnMavenCentral --parallel
-            else
-              ./gradlew createStagingRepositoryOnMavenCentral --parallel
-            fi
-      - name: Save staging repository ID
-        id: staging-repo
-        run: |
-          [[ -f build/staging-repo-ids.properties ]] || (
-            echo "Staging repositories ID file not found" &&
-            exit 1
-          )
-          REPO_IDS=$(cat build/staging-repo-ids.properties)
-          echo "Staging repositories IDs:\n$REPO_IDS"
-          echo $REPO_IDS >> $GITHUB_OUTPUT
 
   build:
     needs:
       - check-secrets
-      - staging-repo
-    if: always() && !contains(needs.staging-repo.result, 'failure')
+      - precompute-next-version
+    if: always() && !contains(needs.precompute-next-version.result, 'failure')
     strategy:
       fail-fast: false
       matrix:
-        os: [ windows-2022, macos-14, ubuntu-22.04 ]
+        os: [ windows-2022, macos-14, ubuntu-24.04 ]
     runs-on: ${{ matrix.os }}
+    outputs:
+      staging-repo-id: ${{ steps.staging-repo.outputs.MavenCentral }}
     steps:
       - name: Checkout
-        uses: DanySK/action-checkout@0.2.22
-      - uses: DanySK/build-check-deploy-gradle-action@3.5.25
+        uses: actions/checkout@v4.2.2
         with:
+          fetch-depth: 0
+      - uses: DanySK/build-check-deploy-gradle-action@3.5.25
+        id: staging-repo
+        with:
+          should-deploy: ${{ runner.os == 'macOS' && needs.check-secrets.outputs.run-with-secrets == 'true' }} # Deploy from macOS since it supports all the platforms
           deploy-command: |
-            # Stop gradle on windows
-            ruby -e 'if /^windows-\w+$/ =~ "${{ matrix.os }}" then puts `./gradlew --stop` end'
-            NEXT_VERSION="${{ needs.staging-repo.outputs.next-version }}"
+            NEXT_VERSION="${{ needs.precompute-next-version.outputs.next-version }}"
             OVERRIDE_VERSION=$([[ "$NEXT_VERSION" != "" ]] && echo "-PforceVersion=$(echo $NEXT_VERSION)" || echo "")
-            ./gradlew $OVERRIDE_VERSION -PstagingRepositoryId=${{ needs.staging-repo.outputs.maven-central-repo-id }} uploadAll --parallel
+            ./gradlew createStagingRepositoryOnMavenCentral --parallel
+
+            [[ -f build/staging-repo-ids.properties ]] || (
+              echo "Staging repositories ID file not found" &&
+              exit 1
+            )
+            REPO_IDS=$(cat build/staging-repo-ids.properties)
+            echo "Staging repositories IDs:\n$REPO_IDS"
+            echo $REPO_IDS >> $GITHUB_OUTPUT
+            
+            ./gradlew $OVERRIDE_VERSION -PstagingRepositoryId=$REPO_IDS uploadAll close --parallel
           should-run-codecov: ${{ runner.os == 'Linux' }}
-          should-deploy: ${{ contains(needs.staging-repo.result, 'success') }}
+          codecov-token: ${{ secrets.CODECOV_TOKEN }}
           maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
           maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
           signing-key: ${{ secrets.SIGNING_KEY }}
           signing-password: ${{ secrets.SIGNING_PASSWORD }}
-
-  close-staging-repos:
-    needs:
-      - staging-repo
-      - build
-    runs-on: ubuntu-24.04
-    if: needs.check-secrets.outputs.run-with-secrets == 'true'
-    steps:
-      - name: Checkout the repo
-        uses: actions/checkout@v4.2.2
-      - uses: DanySK/build-check-deploy-gradle-action@3.5.25
-        with:
-          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
-          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          should-run-codecov: false
-          should-deploy: true
-          build-command: true
-          check-command: true
-          deploy-command: |
-            ./gradlew -PstagingRepositoryId=${{ needs.staging-repo.outputs.maven-central-repo-id }} close --parallel
-            if [[ "${{ needs.staging-repo.outputs.will-release }}" == "false" ]]; then
-              ./gradlew -PstagingRepositoryId=${{ needs.staging-repo.outputs.maven-central-repo-id }} drop
-            fi
 
   release:
     concurrency:
@@ -127,9 +89,8 @@ jobs:
       cancel-in-progress: false
     needs:
       - check-secrets
-      - staging-repo
+      - precompute-next-version
       - build
-      - close-staging-repos
     runs-on: ubuntu-24.04
     if: needs.check-secrets.outputs.run-with-secrets == 'true'
     steps:
@@ -137,17 +98,15 @@ jobs:
         uses: actions/checkout@v4.2.2
         with:
           token: ${{ secrets.DEPLOYMENT_TOKEN }}
-      - name: Find the version of Node from package.json
-        id: node-version
-        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT
       - name: Install Node
         uses: actions/setup-node@v4.1.0
         with:
-          node-version: ${{ steps.node-version.outputs.version }}
+          node-version-file: package.json
       - uses: DanySK/build-check-deploy-gradle-action@3.5.25
         env:
-          STAGING_REPO_ID: ${{ needs.staging-repo.outputs.maven-central-repo-id }}
+          STAGING_REPO_ID: ${{ needs.build.outputs.staging-repo-id }}
         with:
+          retries-on-failure: '1'
           build-command: true
           check-command: true
           deploy-command: |
@@ -166,10 +125,9 @@ jobs:
     runs-on: ubuntu-24.04
     needs:
       - check-secrets
-      - staging-repo
-      - close-staging-repos
-      - release
+      - precompute-next-version
       - build
+      - release
     if: >-
       always() && (
         contains(join(needs.*.result, ','), 'failure')
@@ -181,19 +139,19 @@ jobs:
 
   drop-staging-repos:
     needs:
-      - staging-repo
       - success
     runs-on: ubuntu-24.04
     if: always()
     steps:
-      - name: Checkout the repo
-        uses: actions/checkout@v4.2.2
-      - uses: DanySK/build-check-deploy-gradle-action@3.5.25
-        with:
-          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
-          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          should-run-codecov: false
-          should-deploy: true
-          build-command: true
-          check-command: true
-          deploy-command: ./gradlew -PstagingRepositoryId=${{ needs.staging-repo.outputs.maven-central-repo-id }} drop
+      - env:
+          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
+          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
+        run: >
+          curl
+          --request POST
+          --url "https://s01.oss.sonatype.org/service/local/staging/bulk/drop"
+          --header "Accept: application/json"
+          --header "Content-Type: application/json"
+          --data '{"data":{"stagedRepositoryIds":["${{ needs.build.outputs.staging-repo-id }}"]}}'
+          --user "$MAVEN_CENTRAL_USERNAME:$MAVEN_CENTRAL_PASSWORD"
+          --verbose
